### ISSUE TITLE
get trees trimmed

### ISSUE THREAD

**Issue by stevencarlislewalker** [stevencarlislewalker/house#13]

**Comment by LauraTimms** [comment]
Two quotes so far
- Heritage Trees, $850
- Bruce Tree, $30
  Waiting for Kelly's Tree to come quote

**Comment by stevencarlislewalker** [comment]
$30 per hour for Bruce?

**Comment by LauraTimms** [comment]
Sorry, that was $350 for Bruce Tree.
It was $140/hour

**Comment by stevencarlislewalker** [comment]
Isn't this fun!?

**Comment by LauraTimms** [comment]
![screen shot 2013-07-02 at 1 59 16 pm](https://f.cloud.github.com/assets/4908101/738187/29ff7738-e341-11e2-85e2-cc66e2141ad7.png)

**Comment by LauraTimms** [comment]
Emailed Bruce Tree to hire them.  Not sure if they'll need to do a new quote, since its been so long.

**Comment by LauraTimms** [comment]
Bruce tree coming September 30th.

**Comment by stevencarlislewalker** [comment]
Done.
