### ISSUE TITLE
stair/hall railings

### ISSUE THREAD

**Issue by stevencarlislewalker** [stevencarlislewalker/house#14]

**Comment by stevencarlislewalker** [comment]
Call Bill Stainton in the _near_ future

**Comment by stevencarlislewalker** [comment]
Just left a message on Bill's machine.

**Comment by LauraTimms** [comment]
Bill Stainton _does_ love you. One of the messages was from him yesterday. He left a funny message. He's going to try calling again. He can do the railing, but not till the fall.

**Comment by stevencarlislewalker** [comment]
Really eh?  What d'ya think?  Is the fall too long?

**Comment by LauraTimms** [comment]
Bill is a bust. Contacting new people today.
Left a message for Dan Roitner: http://www.handydan.ws/Carpentry.html
Rex Norman will call soon to come by (416-889-1963)
Glenn Locke - left message (416-837-9298)

**Comment by LauraTimms** [comment]
Glenn Locke coming Sept 4 at 9 a.m.
Sent pics to Dan Roitner Sept 3 6:20 p.m.
Still haven't heard back from Rex Norman

**Comment by LauraTimms** [comment]
Dan putting finishing touches on it right now.
